# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: NuGetPublish

on:
  release:
    types: [published]
    tags: "v[0-9]+.[0-9]+.[0-9]+"
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release /p:Version=${VERSION}
    - name: Pack
      run: dotnet pack Leovaria.Extensions.DateOnlyExtensions/Leovaria.Extensions.DateOnlyExtensions.csproj -c Release /p:Version=${VERSION}
    - name: Publish 
      run: dotnet nuget push Leovaria.Extensions.DateOnlyExtensions/bin/Release/*${VERSION}.nupkg --api-key ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json
